- .scrutinizer.yml
- .travis.yml
Attempt in order to re-enable scrutinizer-ci code coverage
> Re-enable scrutinizer code coverage

- config/module.config.php
- src/DoctrineORMModule/Module.php
> Add latest migrations command

- docs/configuration.md
> Fix typo in configuration file markdown.

- .travis.yml
since php 5.3 was dropped in 70c3aa79fd56d630913c8534b35b44160303d4d6
> Removed unnecessary line in travis config

- src/DoctrineORMModule/Version.php
I have forgotten to change version of this lib
:sos: 
ping @Ocramius
> Fixed missing version

- .travis.yml
See https://github.com/doctrine/DoctrineModule/pull/512 for reference.
> Change build paremeters to prevent errors with hhvm and php7

- src/DoctrineORMModule/Yuml/YumlController.php
- src/DoctrineORMModule/Yuml/YumlControllerFactory.php
- tests/DoctrineORMModuleTest/Yuml/YumlControllerTest.php
Yuml.me have deprecated http connection in favor of https ones
> using https for YumController

- .travis.yml
> added php 7.1 in travis

- src/DoctrineORMModule/Service/MigrationsConfigurationFactory.php
This is fix of https://github.com/doctrine/DoctrineModule/issues/603
> fixed dummy writer

- src/DoctrineORMModule/Options/Configuration.php
Corrections to PHPDocs detailed here: https://github.com/doctrine/DoctrineORMModule/pull/529
> Corrected PHPDocs for configuration

- .travis.yml
added php 7.2 in build matrix, nothing special=)
> added php 7.2 in build matrix

- .travis.yml
- composer.json
This also adds a build against dev dependencies to test upcoming versions
#SymfonyConHackday2017
> Allow installing Symfony 4

- config/module.config.php
- docs/migrations.md
- src/DoctrineORMModule/Service/MigrationsConfigurationFactory.php
allow to configure custom template
> allow to configure custom template

- src/DoctrineORMModule/Form/Annotation/AnnotationBuilder.php
- src/DoctrineORMModule/Form/Annotation/ElementAnnotationsListener.php
- src/DoctrineORMModule/Service/DBALConfigurationFactory.php
- src/DoctrineORMModule/Service/SQLLoggerCollectorFactory.php
- src/DoctrineORMModule/Yuml/MetadataGrapher.php
- tests/DoctrineORMModuleTest/ServiceManagerFactory.php
Should we use https://github.com/doctrine/coding-standard here?
> Use Null Coalesce Operator

- .travis.yml
- composer.json
- composer.lock
- changed to phpunit7
- php72 removed from allowed to fail in build
- removed double CS check (7.1 + 7.2) and readded TEST_COVERAGE
> update to phpunit7

- docs/cache.md
- docs/configuration.md
Update links that link to previous version docs
> update broken links

- src/DoctrineORMModule/Service/MigrationsConfigurationFactory.php
When we use doctrine-migrations v2 we can't see output on the console on running commands, for example:
```bash
vendor/bin/doctrine-module migrations:migrate
```
This is because in v2 we do have dependency factory and the same instance of dependency is always used instead of creating new. In the migration configuration factory however we are creating another instance which is not used in dependency factory later on.
> Fix output writer for doctrine-migrations v2 integration

- composer.json
- composer.lock
This PR adds config-provider entry to composer.json extras for consumption by zend-component-installer
> Add composer extras entry for config provider

- composer.json
> Allow Symfony Console 5.0

- src/DoctrineORMModule/Options/DBALConnection.php
- src/DoctrineORMModule/Service/DBALConnectionFactory.php
- tests/DoctrineORMModuleTest/Service/DBALConnectionFactoryTest.php
This feature allows to configure connection to use savepoints.
> Enable use savepoints configuration

- config/module.config.php
Doctrine\Laminas\Hydrator\DoctrineObject changed
> Update module.config.php - rebase
