docs/cache.md
docs/configuration.md

Replaces https://github.com/doctrine/DoctrineModule/pull/412
Note for @Ocramius : we'll really need to clean this alias mess of "my_memcache_alias" when we'll update Doctrine Module for ZF3. The naming is really not intuitive and strange.

Add doc for cache

---

src/DoctrineORMModule/Form/Annotation/ElementAnnotationsListener.php
tests/DoctrineORMModuleTest/Form/ElementAnnotationsListenerTest.php

We only use the ElementAnnationsListener in our application. But when handleRequiredField is triggered with a property unknown by doctrine or a non column field a mapping exception was thrown. This fix will prevent the listener from throwing exceptions at this point.

added extra check in handleRequiredField

---

composer.json
src/DoctrineORMModule/Service/EntityResolverFactory.php
tests/DoctrineORMModuleTest/Service/EntityResolverFactoryTest.php

Fix #370
The minimum stability has been set to alpha until Doctrine 2.5 is officially released (I think we'll be able to do that once tagging).

Use `ResolveTargetEntityListener` as an event subscriber when supported

---

docs/configuration.md
src/DoctrineORMModule/Options/SecondLevelCacheConfiguration.php
src/DoctrineORMModule/Service/ConfigurationFactory.php
tests/DoctrineORMModuleTest/Service/ConfigurationFactoryTest.php

This addresses a missing option when using cache regions that need a file lock. (https://github.com/doctrine/doctrine2/pull/580)

Allow to set file lock for SLC

---

Module.php

means it must be using composer

update comment block in Module.php as no Module::getAutoloaderConfig() 

---

Module.php

I hope I don't missunderstand of https://github.com/doctrine/DoctrineORMModule/pull/388#issuecomment-76683250 As if there is no Module::getAutoloaderConfig() , we can't work without composer /cc @Ocramius ;)

Delete Module.php in root directory

---

.travis.yml

To be compatible with [version in composer.json](https://github.com/doctrine/DoctrineORMModule/blob/51c64bfc5a87148379a03139e0c986c09c81d6af/composer.json#L36)
Bash syntax cleanup
Next idea: running coverage only once?

travis: PHP 5.6, 7.0 nightly added, 5.3 dropped

---

docs/cache.md

Avoid troubles in case of caching module's configuration

Use-case: caching module's configuration

---

CHANGELOG.md

ping @Ocramius 
pulls 400!!! :tada: :balloon: 
* [#199](https://github.com/doctrine/DoctrineORMModule/pull/199) Add 'entity_listener_resolver' config key
* [#281](https://github.com/doctrine/DoctrineORMModule/pull/281) Forced failing unit test for #247
* [#306](https://github.com/doctrine/DoctrineORMModule/pull/306) Removing PHP 5.3.3 support
* [#272](https://github.com/doctrine/DoctrineORMModule/pull/272) Fix and test #270, #242, #285
* [#311](https://github.com/doctrine/DoctrineORMModule/pull/311) remove unused statement
* [#326](https://github.com/doctrine/DoctrineORMModule/pull/326) Highlight only uppercase words
* [#329](https://github.com/doctrine/DoctrineORMModule/pull/329) remove unused statements
* [#328](https://github.com/doctrine/DoctrineORMModule/pull/328) wrong var …

Changelog release 0.9.0

---

composer.json
tests/DoctrineORMModuleTest/Assets/RepositoryClass.php

Because of phpunit set to ~3.7, DoctrineORMModule was stuck to ZF 2.4.*
PHPCodeSniffer has been updated to ~2 too.

Bump some dependencies versions to be ZF 2.5 compliant

---

config/module.config.php
docs/migrations.md
src/DoctrineORMModule/Service/MigrationsConfigurationFactory.php

Depends on doctrine/migrations#383 being merged, this allows configuration of the migration column name via the MigrationsConfigurationFactory.

Added ability to configure the version column in MigrationsConfigurationFactory

---

composer.json
composer.lock
config/controllers.config.php
config/module.config.php
src/DoctrineORMModule/Service/DBALConfigurationFactory.php
src/DoctrineORMModule/Service/MigrationsConfigurationFactory.php
src/DoctrineORMModule/Service/SQLLoggerCollectorFactory.php
src/DoctrineORMModule/Yuml/YumlControllerFactory.php
tests/DoctrineORMModuleTest/Service/ConfigurationFactoryTest.php
tests/DoctrineORMModuleTest/Service/DBALConnectionFactoryTest.php
tests/DoctrineORMModuleTest/Service/SQLLoggerCollectorFactoryTest.php
tests/DoctrineORMModuleTest/Yuml/YumlControllerFactoryTest.php

- Fixed route to be compatible with both `zend-mvc`<3.0 and `zend-router`. The route configuration is moved to the Module class implementing `RouteProviderInterface`.
- Replaced `Config` key with the standardized and lowercased `config` key.

Hotfix router config

---

composer.json

There is new library used with zend application skeleton and apigility skeleton to simplify installation of new modules: [`zend-component-installer`](https://github.com/zendframework/zend-component-installer).

Expose to `zend-component-installer` as module `DoctrineORMModule`

---

composer.json

Decreased composer dependencies of zend modules to match dependencies in ZendSkeletonApplication.
Currently if we build new project using composer `create-project` (from `ZendSkeletonApplication`) we have to run `composer update` because locked dependencies there are lower than required here.
We can safely decrees these dependencies in this library.

ZF3 Composer dependencies - hotfix

---

view/zend-developer-tools/toolbar/doctrine-orm-queries.phtml

Fixes the error 'A plugin by the name "zendDeveloperToolsTime" was not found in the plugin manager'

Fix: Missing view helper "zendDeveloperToolsTime"

---

docs/EXTRAS_ORM.md

As there is no reference to be found to my_dbal_default I found that the correct value needs to be orm_default, as goes for all the other configuration elements.

Update to EXTRA_ORM.md to correct config key

---

composer.json
composer.lock

Thanks @gianarb for DoctrineModule 1.2.0 release with ZF3 compatibility ! 👍

Require stable version of DoctrineModule 1.2.0 instead of dev-master

---

.gitignore
composer.json
composer.lock
tests/DoctrineORMModuleTest/Collector/MappingCollectorTest.php
tests/DoctrineORMModuleTest/Form/AnnotationBuilderTest.php
tests/DoctrineORMModuleTest/Form/ElementAnnotationsListenerTest.php
tests/DoctrineORMModuleTest/Options/ConfigurationOptionsTest.php
tests/DoctrineORMModuleTest/Options/DBALConnectionTest.php
tests/DoctrineORMModuleTest/Options/DefaultRepositoryTest.php
tests/DoctrineORMModuleTest/Service/ConfigurationFactoryTest.php
tests/DoctrineORMModuleTest/Service/DBALConnectionFactoryTest.php
tests/DoctrineORMModuleTest/Service/FormAnnotationBuilderFactoryTest.php
tests/DoctrineORMModuleTest/Service/MigrationsCommandFactoryTest.php
tests/DoctrineORMModuleTest/Service/SQLLoggerCollectorFactoryTest.php
tests/DoctrineORMModuleTest/ServiceManagerFactory.php
tests/DoctrineORMModuleTest/Yuml/MetadataGrapherTest.php
tests/DoctrineORMModuleTest/Yuml/YumlControllerFactoryTest.php
tests/DoctrineORMModuleTest/Yuml/YumlControllerTest.php
tests/TestConfigurationV2.php
tests/TestConfigurationV3.php
tests/testing.config.php

changed `getMock` to `getMockBuilder` for PHPUnit 5.4+
changed `setExpectedException` to `expectException` it is already deprecated
changed arraysyntax in unittests
updated composer.json to min PHPUnit 5.5.0

PHPUnit update

---

src/DoctrineORMModule/Service/DBALConnectionFactory.php
tests/DoctrineORMModuleTest/Service/DBALConnectionFactoryTest.php

Hi guys,
We sometimes got the issue that our app can't connect to our database.
Right now we just get a "ServiceNotCreatedException", because the DBALConnectionFactory opens a db connection while creating the connection services.
This fix only opens a db connection, if needed.
That way we can catch the ConnectionException in our controller/business logic and return a proper response.

DBALConnectionFactory opens db connection, even if its not necessary

---

src/DoctrineORMModule/Module.php
tests/DoctrineORMModuleTest/CliTest.php

Added a option to use a different entity-manager on cli.
Name: **doctrine.entitymanager.orm_default**
`php public/index.php orm:schema-tool:update --dump-sql `
Name: **doctrine.entitymanager.some_other**
`php public/index.php orm:schema-tool:update --dump-sql --entitymanager=some_other`
Inspired by the "doctrine/doctrine-mongo-odm-module" --documentmanager option.

Added a option to use a different entity-manager on cli

---

src/DoctrineORMModule/ConfigProvider.php
tests/DoctrineORMModuleTest/ConfigProviderTest.php

Many ZF components now use a `ConfigProvider` to assist in config merging and allow components to be used e.g. in Expressive.
I took the strategy of least interference with existing config loading, so I did not move config here, nor make `Module.php` load config using the `ConfigProvider`. If desired, however, I can add this functionality into this PR. Feedback welcome, thanks!

Added ConfigProvider in line with ZF components

---

.travis.yml
composer.json
composer.lock
tests/DoctrineORMModuleTest/CliTest.php
tests/DoctrineORMModuleTest/Collector/MappingCollectorTest.php
tests/DoctrineORMModuleTest/Collector/SQLLoggerCollectorTest.php
tests/DoctrineORMModuleTest/ConfigProviderTest.php
tests/DoctrineORMModuleTest/Form/ElementAnnotationsListenerTest.php
tests/DoctrineORMModuleTest/Framework/TestCase.php
tests/DoctrineORMModuleTest/Options/ConfigurationOptionsTest.php
tests/DoctrineORMModuleTest/Options/DBALConnectionTest.php
tests/DoctrineORMModuleTest/Options/EntityManagerTest.php
tests/DoctrineORMModuleTest/Options/SQLLoggerCollectorOptionsTest.php
tests/DoctrineORMModuleTest/Service/ConfigurationFactoryTest.php
tests/DoctrineORMModuleTest/Service/DBALConnectionFactoryTest.php
tests/DoctrineORMModuleTest/Service/FormAnnotationBuilderFactoryTest.php
tests/DoctrineORMModuleTest/Service/MigrationsCommandFactoryTest.php
tests/DoctrineORMModuleTest/Service/SQLLoggerCollectorFactoryTest.php
tests/DoctrineORMModuleTest/Yuml/MetadataGrapherTest.php
tests/DoctrineORMModuleTest/Yuml/YumlControllerFactoryTest.php
tests/DoctrineORMModuleTest/Yuml/YumlControllerTest.php

- PHPUnit_Framework_TestCase changed to namespace
- composer update, add phpunit 6.2
- phpunit/phpunit added as LEGACY_DEPS in travis build
- generate composer.lock with php 5.6.30, zend-mvc 2.7 and phpunit 5.7
@TomHAnderson like in https://github.com/doctrine/DoctrineORMModule/pull/508 written =)

PHPUnit 6 support added

---

src/DoctrineORMModule/Options/Configuration.php
src/DoctrineORMModule/Service/ConfigurationFactory.php

Added schema_filter (setFilterSchemaAssetsExpression) support for Zend in the configuration file like in symfony, described here: https://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#manual-tables

Support for FilterSchemaAssetsExpression

---

.travis.yml

like in [zf-blog](https://framework.zend.com/blog/2017-06-06-zf-php-7-1.html) written removed hhvm
also the current hhvm tests go to a vm error, so it was not realy testet

drop hhvm from travis

---

src/DoctrineORMModule/Service/DBALConnectionFactory.php
tests/DoctrineORMModuleTest/Service/DBALConnectionFactoryTest.php

This PR allows to retrieve platform from container.
The `platform` param must be an instance, but it's impossible to set an instance in the configuration (if we want to cache it). So, if we provide a string, we should check if can be retrieved from the service container.

Allow retrieving platform from container

---

config/module.config.php
src/DoctrineORMModule/CliConfigurator.php
src/DoctrineORMModule/Listener/PostCliLoadListener.php
src/DoctrineORMModule/Module.php
src/DoctrineORMModule/Service/CliConfiguratorFactory.php
src/DoctrineORMModule/Service/PostCliLoadListenerFactory.php
tests/DoctrineORMModuleTest/CliConfiguratorTest.php
tests/DoctrineORMModuleTest/CliTest.php
tests/DoctrineORMModuleTest/Listener/PostCliLoadListenerTest.php
tests/TestConfigurationV2.php
tests/TestConfigurationV3.php

Hi!
This PR is not adding any features, it's merely the start of a refactoring in order to split responsibilities in some of the existing classes. The goal is to get out the logic that initializes the console application from the `DoctrineORMModule\Module` class.
* the listener of `loadCli.post` event, that aims to initialize console application, is separated in it's own file and class:`DoctrineORMModule\Listener\PostCliLoadListener`
* `DoctrineORMModule\CliConfigurator` class is used to configure console application in the previous listener. This class has been splitted into several methods that could lead to the creation of other classes to improve separation of concerns.
* consequently, unit tests have been updated and improved

Uses listener class to configure console application

---

docs/configuration.md

In the documentation for using multiple connection is written that we should register 8 factories to make the new connection, Entity-Manager, etc ... work. See https://github.com/doctrine/DoctrineORMModule/blob/master/docs/configuration.md#how-to-use-two-connections
This worked well in dev, but fails everywhere else! 
```
Error: Call to undefined method DoctrineORMModule\Service\DBALConnectionFactory::__set_state() in /x/data/module-config-cache.php:187
Stack trace:
#0 /x/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(392): include()
#1 /x/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(70): Zend\ModuleManager\Listener\ConfigListener->getCachedConfig()
#2 /x/vendor/zendframework/zend-modulemanager/src/Listener/DefaultListenerAggregate.php(11 …
```

[DOCS] Fix the documentation for using multiple connections

---

docs/cache.rst
docs/developer-tools.rst

image link in documentation result in mixed content problem

---

tests/DoctrineORMModuleTest/Collector/SQLLoggerCollectorTest.php

I received this error when testing:
```
1) DoctrineORMModuleTest\Collector\SQLLoggerCollectorTest::testGetQueryTime
Failed asserting that 1.9073486328125E-6 is greater than 1.9073486328125E-6.
```
To allow measurable time to pass I added a sleep(1) to this test

Allow for measurable time to pass when testing SQLLogger GetQueryTime

---

src/DoctrineORMModule/Service/MappingCollectorFactory.php

Fixes `Fatal Error (E_COMPILE_ERROR): Declaration of DoctrineORMModule\Service\MappingCollectorFactory::getOptionsClass() must be compatible with DoctrineModule\Service\AbstractFactory::getOptionsClass(): string`

Fix fatal error

---

src/DoctrineORMModule/Form/Annotation/ElementAnnotationsListener.php

Latest doctrine coding standard flags nesting of control structures per method as small as possible.  Fixed.

Fix nesting of control structures per method as small as possible
